
CREATE TABLE "AuditLogs" (
    "Id" uuid NOT NULL,
    "Action" character varying(100) NOT NULL,
    "EntityType" character varying(50) NOT NULL,
    "EntityId" uuid NOT NULL,
    "UserId" uuid,
    "UserEmail" character varying(256),
    "UserName" character varying(200),
    "Details" jsonb,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
);


CREATE TABLE "CompetencyTypes" (
    "Id" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(500),
    "Category" character varying(100),
    "RequiresExpiration" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_CompetencyTypes" PRIMARY KEY ("Id")
);


CREATE TABLE "EquipmentCategories" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(300),
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_EquipmentCategories" PRIMARY KEY ("Id")
);


CREATE TABLE "JobTitles" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "IsLeader" boolean NOT NULL DEFAULT FALSE,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_JobTitles" PRIMARY KEY ("Id")
);


CREATE TABLE "Permissions" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "Category" character varying(100) NOT NULL,
    CONSTRAINT "PK_Permissions" PRIMARY KEY ("Id")
);


CREATE TABLE "EquipmentItems" (
    "Id" uuid NOT NULL,
    "CategoryId" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "HasSize" boolean NOT NULL DEFAULT FALSE,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_EquipmentItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EquipmentItems_EquipmentCategories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "EquipmentCategories" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id")
);


CREATE TABLE "AspNetRoles" (
    "Id" uuid NOT NULL,
    "Description" character varying(250) NOT NULL,
    "IsSystem" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedById" uuid,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);


CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id")
);


CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey")
);


CREATE TABLE "AspNetUserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUsers" (
    "Id" uuid NOT NULL,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "JobTitleId" uuid,
    "EmploymentType" character varying(20) NOT NULL,
    "IsActive" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ManagerId" uuid,
    "DepartmentId" uuid NOT NULL,
    "CreatedById" uuid,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUsers_AspNetUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_AspNetUsers_AspNetUsers_ManagerId" FOREIGN KEY ("ManagerId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_AspNetUsers_JobTitles_JobTitleId" FOREIGN KEY ("JobTitleId") REFERENCES "JobTitles" ("Id") ON DELETE SET NULL
);


CREATE TABLE "AspNetUserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Competencies" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "CompetencyTypeId" uuid NOT NULL,
    "Status" character varying(20) NOT NULL,
    "ExpiryDate" timestamp with time zone,
    "IssuedDate" timestamp with time zone NOT NULL,
    "CertificateNumber" character varying(100),
    "Notes" character varying(2000),
    "RevokedAt" timestamp with time zone,
    "RevokedReason" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Competencies" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Competencies_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Competencies_CompetencyTypes_CompetencyTypeId" FOREIGN KEY ("CompetencyTypeId") REFERENCES "CompetencyTypes" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "Departments" (
    "Id" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "ParentDepartmentId" uuid,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ManagerId" uuid,
    "CreatedById" uuid,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Departments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Departments_AspNetUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Departments_AspNetUsers_ManagerId" FOREIGN KEY ("ManagerId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Departments_Departments_ParentDepartmentId" FOREIGN KEY ("ParentDepartmentId") REFERENCES "Departments" ("Id") ON DELETE SET NULL
);


CREATE TABLE "DocumentTypes" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Slug" character varying(50) NOT NULL,
    "Description" character varying(500),
    "TargetMode" character varying(20) NOT NULL,
    "StorageFolder" character varying(100) NOT NULL,
    "AllowedMimeTypes" text[] NOT NULL,
    "MaxFileSizeBytes" bigint NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedById" uuid,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_DocumentTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DocumentTypes_AspNetUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL
);


CREATE TABLE "EquipmentIssuances" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "ItemId" uuid NOT NULL,
    "IssuedById" uuid NOT NULL,
    "Quantity" integer NOT NULL DEFAULT 1,
    "Size" character varying(20),
    "IssuedDate" timestamp with time zone NOT NULL,
    "Notes" character varying(500),
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_EquipmentIssuances" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EquipmentIssuances_AspNetUsers_IssuedById" FOREIGN KEY ("IssuedById") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_EquipmentIssuances_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_EquipmentIssuances_EquipmentItems_ItemId" FOREIGN KEY ("ItemId") REFERENCES "EquipmentItems" ("Id") ON DELETE CASCADE
);


CREATE TABLE "OtpCodes" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Code" character varying(64) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "IsUsed" boolean NOT NULL,
    "FailedAttempts" integer NOT NULL,
    "LastAttemptAt" timestamp with time zone,
    CONSTRAINT "PK_OtpCodes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OtpCodes_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "RefreshTokens" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Token" character varying(128) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "IsRevoked" boolean NOT NULL,
    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RefreshTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "RolePermissions" (
    "RoleId" uuid NOT NULL,
    "PermissionId" uuid NOT NULL,
    "GrantedAt" timestamp with time zone NOT NULL,
    "GrantedById" uuid,
    CONSTRAINT "PK_RolePermissions" PRIMARY KEY ("RoleId", "PermissionId"),
    CONSTRAINT "FK_RolePermissions_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RolePermissions_AspNetUsers_GrantedById" FOREIGN KEY ("GrantedById") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_RolePermissions_Permissions_PermissionId" FOREIGN KEY ("PermissionId") REFERENCES "Permissions" ("Id") ON DELETE CASCADE
);


CREATE TABLE "CompetencyNotificationLogs" (
    "Id" uuid NOT NULL,
    "CompetencyId" uuid NOT NULL,
    "ThresholdDays" integer NOT NULL,
    "RecipientEmail" character varying(256) NOT NULL,
    "RecipientRole" character varying(20) NOT NULL,
    "SentAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_CompetencyNotificationLogs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CompetencyNotificationLogs_Competencies_CompetencyId" FOREIGN KEY ("CompetencyId") REFERENCES "Competencies" ("Id") ON DELETE CASCADE
);


CREATE TABLE "DocumentTypeCategories" (
    "Id" uuid NOT NULL,
    "DocumentTypeId" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Slug" character varying(50) NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_DocumentTypeCategories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DocumentTypeCategories_DocumentTypes_DocumentTypeId" FOREIGN KEY ("DocumentTypeId") REFERENCES "DocumentTypes" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Documents" (
    "Id" uuid NOT NULL,
    "DocumentTypeId" uuid NOT NULL,
    "DocumentTypeCategoryId" uuid,
    "Title" character varying(200) NOT NULL,
    "Description" character varying(2000),
    "ExternalUrl" character varying(500),
    "RequiresSignature" boolean NOT NULL DEFAULT TRUE,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "Version" integer NOT NULL,
    "FileName" character varying(255),
    "FilePath" character varying(500),
    "FileSize" bigint,
    "MimeType" character varying(100),
    "Checksum" character varying(64),
    "UploadedBy" uuid NOT NULL,
    "UploadedAt" timestamp with time zone NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Documents" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Documents_AspNetUsers_UploadedBy" FOREIGN KEY ("UploadedBy") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Documents_DocumentTypeCategories_DocumentTypeCategoryId" FOREIGN KEY ("DocumentTypeCategoryId") REFERENCES "DocumentTypeCategories" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Documents_DocumentTypes_DocumentTypeId" FOREIGN KEY ("DocumentTypeId") REFERENCES "DocumentTypes" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "DocumentDepartments" (
    "DocumentId" uuid NOT NULL,
    "DepartmentId" uuid NOT NULL,
    CONSTRAINT "PK_DocumentDepartments" PRIMARY KEY ("DocumentId", "DepartmentId"),
    CONSTRAINT "FK_DocumentDepartments_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_DocumentDepartments_Documents_DocumentId" FOREIGN KEY ("DocumentId") REFERENCES "Documents" ("Id") ON DELETE CASCADE
);


CREATE TABLE "DocumentJobTitles" (
    "DocumentId" uuid NOT NULL,
    "JobTitleId" uuid NOT NULL,
    CONSTRAINT "PK_DocumentJobTitles" PRIMARY KEY ("DocumentId", "JobTitleId"),
    CONSTRAINT "FK_DocumentJobTitles_Documents_DocumentId" FOREIGN KEY ("DocumentId") REFERENCES "Documents" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_DocumentJobTitles_JobTitles_JobTitleId" FOREIGN KEY ("JobTitleId") REFERENCES "JobTitles" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "DocumentSignatures" (
    "Id" uuid NOT NULL,
    "DocumentId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "SignedAt" timestamp with time zone NOT NULL,
    "SignatureVersion" integer NOT NULL,
    CONSTRAINT "PK_DocumentSignatures" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DocumentSignatures_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_DocumentSignatures_Documents_DocumentId" FOREIGN KEY ("DocumentId") REFERENCES "Documents" ("Id") ON DELETE CASCADE
);


CREATE TABLE "DocumentVersions" (
    "Id" uuid NOT NULL,
    "DocumentId" uuid NOT NULL,
    "Version" integer NOT NULL,
    "FileName" character varying(255),
    "FilePath" character varying(500),
    "FileSize" bigint,
    "MimeType" character varying(100),
    "Checksum" character varying(64),
    "ArchivedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_DocumentVersions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DocumentVersions_Documents_DocumentId" FOREIGN KEY ("DocumentId") REFERENCES "Documents" ("Id") ON DELETE CASCADE
);


CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");


CREATE INDEX "IX_AspNetRoles_CreatedById" ON "AspNetRoles" ("CreatedById");


CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");


CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");


CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");


CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");


CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");


CREATE INDEX "IX_AspNetUsers_CreatedById" ON "AspNetUsers" ("CreatedById");


CREATE INDEX "IX_AspNetUsers_DeletedAt" ON "AspNetUsers" ("DeletedAt");


CREATE INDEX "IX_AspNetUsers_DepartmentId" ON "AspNetUsers" ("DepartmentId");


CREATE INDEX "IX_AspNetUsers_JobTitleId" ON "AspNetUsers" ("JobTitleId");


CREATE INDEX "IX_AspNetUsers_ManagerId" ON "AspNetUsers" ("ManagerId");


CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");


CREATE INDEX "IX_AuditLogs_Action" ON "AuditLogs" ("Action");


CREATE INDEX "IX_AuditLogs_CreatedAt" ON "AuditLogs" ("CreatedAt" DESC);


CREATE INDEX "IX_AuditLogs_EntityType_EntityId" ON "AuditLogs" ("EntityType", "EntityId");


CREATE INDEX "IX_AuditLogs_EntityType_EntityId_CreatedAt" ON "AuditLogs" ("EntityType", "EntityId", "CreatedAt" DESC);


CREATE INDEX "IX_AuditLogs_UserId" ON "AuditLogs" ("UserId");


CREATE INDEX "IX_Competencies_CompetencyTypeId" ON "Competencies" ("CompetencyTypeId");


CREATE INDEX "IX_Competencies_DeletedAt" ON "Competencies" ("DeletedAt");


CREATE INDEX "IX_Competencies_ExpiryDate" ON "Competencies" ("ExpiryDate");


CREATE INDEX "IX_Competencies_Status" ON "Competencies" ("Status");


CREATE INDEX "IX_Competencies_UserId_CompetencyTypeId" ON "Competencies" ("UserId", "CompetencyTypeId");


CREATE INDEX "IX_CompetencyNotificationLogs_CompetencyId_ThresholdDays" ON "CompetencyNotificationLogs" ("CompetencyId", "ThresholdDays");


CREATE UNIQUE INDEX "IX_CompetencyNotificationLogs_CompetencyId_ThresholdDays_Recip~" ON "CompetencyNotificationLogs" ("CompetencyId", "ThresholdDays", "RecipientEmail");


CREATE INDEX "IX_CompetencyTypes_Category" ON "CompetencyTypes" ("Category");


CREATE INDEX "IX_CompetencyTypes_DeletedAt" ON "CompetencyTypes" ("DeletedAt");


CREATE INDEX "IX_Departments_CreatedById" ON "Departments" ("CreatedById");


CREATE INDEX "IX_Departments_DeletedAt" ON "Departments" ("DeletedAt");


CREATE INDEX "IX_Departments_ManagerId" ON "Departments" ("ManagerId");


CREATE INDEX "IX_Departments_ParentDepartmentId" ON "Departments" ("ParentDepartmentId");


CREATE INDEX "IX_DocumentDepartments_DepartmentId" ON "DocumentDepartments" ("DepartmentId");


CREATE INDEX "IX_DocumentJobTitles_JobTitleId" ON "DocumentJobTitles" ("JobTitleId");


CREATE INDEX "IX_Documents_DeletedAt" ON "Documents" ("DeletedAt");


CREATE INDEX "IX_Documents_DocumentTypeCategoryId" ON "Documents" ("DocumentTypeCategoryId");


CREATE INDEX "IX_Documents_DocumentTypeId_IsActive" ON "Documents" ("DocumentTypeId", "IsActive");


CREATE INDEX "IX_Documents_UploadedBy" ON "Documents" ("UploadedBy");


CREATE UNIQUE INDEX "IX_DocumentSignatures_DocumentId_UserId_SignatureVersion" ON "DocumentSignatures" ("DocumentId", "UserId", "SignatureVersion");


CREATE INDEX "IX_DocumentSignatures_UserId" ON "DocumentSignatures" ("UserId");


CREATE UNIQUE INDEX "IX_DocumentTypeCategories_DocumentTypeId_Slug" ON "DocumentTypeCategories" ("DocumentTypeId", "Slug") WHERE "DeletedAt" IS NULL;


CREATE INDEX "IX_DocumentTypes_CreatedById" ON "DocumentTypes" ("CreatedById");


CREATE INDEX "IX_DocumentTypes_DeletedAt" ON "DocumentTypes" ("DeletedAt");


CREATE UNIQUE INDEX "IX_DocumentTypes_Slug" ON "DocumentTypes" ("Slug");


CREATE UNIQUE INDEX "IX_DocumentVersions_DocumentId_Version" ON "DocumentVersions" ("DocumentId", "Version");


CREATE INDEX "IX_EquipmentCategories_DeletedAt" ON "EquipmentCategories" ("DeletedAt");


CREATE UNIQUE INDEX "IX_EquipmentCategories_Name" ON "EquipmentCategories" ("Name") WHERE "DeletedAt" IS NULL;


CREATE INDEX "IX_EquipmentIssuances_DeletedAt" ON "EquipmentIssuances" ("DeletedAt");


CREATE INDEX "IX_EquipmentIssuances_IssuedById" ON "EquipmentIssuances" ("IssuedById");


CREATE INDEX "IX_EquipmentIssuances_ItemId" ON "EquipmentIssuances" ("ItemId");


CREATE INDEX "IX_EquipmentIssuances_UserId" ON "EquipmentIssuances" ("UserId");


CREATE INDEX "IX_EquipmentItems_CategoryId" ON "EquipmentItems" ("CategoryId");


CREATE UNIQUE INDEX "IX_EquipmentItems_CategoryId_Name" ON "EquipmentItems" ("CategoryId", "Name") WHERE "DeletedAt" IS NULL;


CREATE INDEX "IX_EquipmentItems_DeletedAt" ON "EquipmentItems" ("DeletedAt");


CREATE INDEX "IX_JobTitles_DeletedAt" ON "JobTitles" ("DeletedAt");


CREATE UNIQUE INDEX "IX_JobTitles_Name" ON "JobTitles" ("Name") WHERE "DeletedAt" IS NULL;


CREATE UNIQUE INDEX "IX_OtpCodes_UserId" ON "OtpCodes" ("UserId") WHERE "IsUsed" = false;


CREATE UNIQUE INDEX "IX_Permissions_Name" ON "Permissions" ("Name");


CREATE UNIQUE INDEX "IX_RefreshTokens_Token" ON "RefreshTokens" ("Token");


CREATE INDEX "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");


CREATE INDEX "IX_RolePermissions_GrantedById" ON "RolePermissions" ("GrantedById");


CREATE INDEX "IX_RolePermissions_PermissionId" ON "RolePermissions" ("PermissionId");


ALTER TABLE "AspNetRoleClaims" ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE;


ALTER TABLE "AspNetRoles" ADD CONSTRAINT "FK_AspNetRoles_AspNetUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL;


ALTER TABLE "AspNetUserClaims" ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;


ALTER TABLE "AspNetUserLogins" ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;


ALTER TABLE "AspNetUserRoles" ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;


ALTER TABLE "AspNetUsers" ADD CONSTRAINT "FK_AspNetUsers_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id") ON DELETE SET NULL;



